// BIND9 primary — nginx EC2 (172.31.83.161)
// Source de vérité de la zone nexusplay.local

options {
    listen-on port 53 { any; };
    listen-on-v6 port 53 { none; };
    directory       "/var/named";
    dump-file       "/var/named/data/cache_dump.db";
    statistics-file "/var/named/data/named_stats.txt";
    memstatistics-file "/var/named/data/named_mem_stats.txt";
    recursing-file  "/var/named/data/named.recursing";
    secroots-file   "/var/named/data/named.secroots";

    allow-query     { any; };
    allow-transfer  { 172.31.85.185; };   // nginx2 (secondary) only
    also-notify     { 172.31.85.185; };

    recursion no;                          // pas de résolveur récursif (autoritaire seulement)
    dnssec-validation no;

    pid-file "/run/named/named.pid";
    session-keyfile "/run/named/session.key";
};

logging {
    channel default_debug {
        file "data/named.run";
        severity dynamic;
    };
};

zone "nexusplay.local" IN {
    type master;
    file "nexusplay.local.zone";
    allow-update { none; };
    notify yes;
};
