upstream frontend {
    server 172.31.80.143:3000;
}

upstream backend {
    least_conn;
    server 172.31.85.135:8080 max_fails=2 fail_timeout=10s;
    server 172.31.85.135:8081 max_fails=2 fail_timeout=10s;
    server 172.31.85.135:8082 max_fails=2 fail_timeout=10s;
    server 172.31.85.135:8083 max_fails=2 fail_timeout=10s backup;
    server 172.31.85.135:8084 max_fails=2 fail_timeout=10s backup;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80 default_server;
    server_name _;

    access_log /var/log/nginx/nexusplay_access.log;
    error_log  /var/log/nginx/nexusplay_error.log;

    client_max_body_size 10m;

    location /health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    location /api/ {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;
        proxy_read_timeout 60s;
    }

    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;
    }
}
