// BIND9 secondary — nginx2 EC2 (172.31.85.185)
// Réplique en lecture, demande la zone au primary via AXFR

options {
    listen-on port 53 { any; };
    listen-on-v6 port 53 { none; };
    directory       "/var/named";
    dump-file       "/var/named/data/cache_dump.db";
    statistics-file "/var/named/data/named_stats.txt";
    memstatistics-file "/var/named/data/named_mem_stats.txt";
    recursing-file  "/var/named/data/named.recursing";
    secroots-file   "/var/named/data/named.secroots";

    allow-query     { any; };
    allow-transfer  { none; };

    recursion no;
    dnssec-validation no;

    pid-file "/run/named/named.pid";
    session-keyfile "/run/named/session.key";
};

logging {
    channel default_debug {
        file "data/named.run";
        severity dynamic;
    };
};

zone "nexusplay.local" IN {
    type slave;
    file "slaves/nexusplay.local.zone";
    masters { 172.31.83.161; };   // primary BIND9 = nginx EC2
    masterfile-format text;
};
